name = "sigandsys-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables for all environments
[vars]
ENVIRONMENT = "development"

# Production environment configuration
[env.production]
name = "sigandsys-api"
[env.production.vars]
ENVIRONMENT = "production"

# Staging environment configuration 
[env.staging]
name = "sigandsys-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

# Local development secrets (use .dev.vars file or wrangler secret commands)
# For local development, create a .dev.vars file with:
# SENDGRID_API_KEY=your_api_key_here
#
# For production deployment, use:
# wrangler secret put SENDGRID_API_KEY --env production
# wrangler secret put SENDGRID_API_KEY --env staging

# Example KV namespace (uncomment when needed)
# [[kv_namespaces]]
# binding = "SIGANDSYS_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Example D1 database (uncomment when needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "sigandsys-db"
# database_id = "your-database-id"